---
default_language_version:
  python: python3.14
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: ^md2enex/xml_cache/
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint-system
  - repo: https://github.com/executablebooks/mdformat
    rev: 2d496dbc18e31b83a1596685347ffe0b6041daf0  # frozen: 1.0.0
    hooks:
      - id: mdformat
        exclude: ^tests/test4/test4.markdownyaml.md$
        additional_dependencies:
          - mdformat-gfm
          - mdformat-toc
